### ISSUE TITLE
about language model

### ISSUE THREAD

**Issue by dopc** [RashadGarayev/TRSpeech-to-text#3]
Hey, thanks for great work and sharing it.

I want to ask about https://github.com/RashadGarayev/TRSpeech-to-text#pre-trained-turkish-model.

- Which corpus did you use?
- As I see, it is 2-gram model. Is there a 3- or 4-gram model which you can share?

Looking forward for your answer.
Thanks

**Comment by RashadGarayev** [comment]
Open source dataset https://commonvoice.mozilla.org/en/datasets - select turkish lang

**Comment by dopc** [comment]
Thanks for your answer.
But I have asked for textual language model and its corpus.

> For the language model, I used kenlm’ lmplz -o 2 < vocabulary > text.arpa build_binary text.arpa lm.binary

in this command, 

> vocabulary

and

> text.arpa

or

> lm.binary

many thanks.

**Comment by RashadGarayev** [comment]
You can parse texts from the Internet. Minimum 10 thousand sentences

**Comment by dopc** [comment]
okay, thanks so much!
